name: Go

on:
  push:
    tags:
      - '*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build (linux/arm)
      env:
        GOOS: linux
        GOARCH: arm
      run: go build -o build/onvif_record_linux-arm -v .
    
    - name: Build (linux/amd64)
      env:
        GOOS: linux
        GOARCH: amd64
      run: go build -o build/onvif_record_linux-amd64 -v .
      
    - name: Build (freebsd/amd64)
      env:
        GOOS: freebsd
        GOARCH: amd64
      run: go build -o build/onvif_record_freebsd-amd64 -v .
  
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tagName.outputs.tag }}
        release_name: Release ${{ steps.tagName.outputs.tag }}
    
    - name: Upload freebsd/amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/onvif_record_freebsd-amd64
        asset_name: onvif_record_freebsd-amd64
        asset_content_type: application/octet-stream
        
    - name: Upload linux/amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/onvif_record_linux-amd64
        asset_name: onvif_record_linux-amd64
        asset_content_type: application/octet-stream
    
    - name: Upload linux/arm
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/onvif_record_linux-arm
        asset_name: onvif_record_linux-arm
        asset_content_type: application/octet-stream
